# Generated by Django 4.1.2 on 2022-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.TextField()),
                ('name', models.TextField()),
                ('result', models.BooleanField()),
                ('category', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
