# Generated by Django 4.1.2 on 2022-12-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cardorSamsung',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='hp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='option',
            field=models.TextField(null=True),
        ),
    ]
